# Generated by Django 3.2.8 on 2021-10-24 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=30)),
                ('last_name', models.CharField(default='', max_length=30)),
                ('mobile_phone', models.CharField(default='', max_length=10)),
                ('work_phone', models.CharField(blank=True, default='', max_length=10)),
                ('comments', models.CharField(blank=True, default='', max_length=200)),
            ],
        ),
    ]
