# Generated by Django 3.2.8 on 2021-10-24 09:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('property', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=200)),
                ('skillset_required', models.CharField(default='', max_length=200)),
                ('severity_level', models.CharField(default='', max_length=20)),
                ('current_status', models.CharField(default='', max_length=25)),
                ('desired_completion_date', models.DateTimeField(blank=True)),
                ('actual_completion_date', models.DateTimeField(blank=True)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default='0.0', max_digits=8)),
                ('actual_cost', models.DecimalField(decimal_places=2, default='0.0', max_digits=8)),
                ('apartment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.apartment')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('item_cost', models.DecimalField(decimal_places=2, default='0.0', max_digits=8)),
                ('work_order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='work_order.workorder')),
            ],
        ),
    ]
