# Generated by Django 3.2.8 on 2021-10-24 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('client', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(default='', max_length=30)),
                ('street_address', models.CharField(default='', max_length=40)),
                ('city', models.CharField(default='', max_length=20)),
                ('state', models.CharField(default='NE', max_length=2)),
                ('zipcode', models.CharField(default='00000', max_length=9)),
                ('age_in_years', models.CharField(blank=True, default='', max_length=2)),
            ],
            options={
                'verbose_name_plural': 'Properties',
            },
        ),
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size_in_sqft', models.IntegerField(default='')),
                ('number_of_bedrooms', models.IntegerField(default='')),
                ('floor', models.IntegerField(default='')),
                ('description', models.CharField(default=' ', max_length=300)),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='client.client')),
                ('property_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='property.property')),
            ],
        ),
    ]
